services:
  app:
    build:
      # For proxies to work
      network: host
      context: .
    container_name: gorest_app
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
    networks:
      - gorest

  db:
    container_name: gorest_db
    image: mariadb:10.7.1-focal
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./docker-storage/mariadb:/var/lib/mysql
    networks:
      - gorest

  cache:
    container_name: gorest_cache
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./docker-storage/redis:/data
    networks:
      - gorest

networks:
  gorest:
    driver: bridge
