services:
  app:
    build:
      # For proxies to work
      network: host
      context: .
    container_name: gorest_app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./.env.docker:/app/.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - gorest

  db:
    container_name: gorest_db
    image: mariadb:10.7.1-focal
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./docker-storage/mariadb:/var/lib/mysql
    networks:
      - gorest
    healthcheck:
      test: mysqladmin ping -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      start_period: 1s
      interval: 2s
      timeout: 2s
      retries: 10

  cache:
    container_name: gorest_cache
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./docker-storage/redis:/data
    networks:
      - gorest
    healthcheck:
      test: "[ $$(redis-cli ping) = 'PONG' ]"
      start_period: 1s
      interval: 2s
      timeout: 2s
      retries: 10

networks:
  gorest:
    driver: bridge
